/* Edit this file to update the portfolio. Add photos to assets/ and set image: "assets/filename.jpg". */
window.portfolio = {
  contact: { email: "", linkedin: "", github: "", resume: "" },
  projects: [
    { id: "therapeutics", number: "01", title: "Therapeutic research", category: "BIOTECH / RESEARCH", summary: "Exploring biological targets and questions in the development of new therapeutics.", color: "peach", motif: "molecule", image: "", context: "Diagonal Therapeutics", overview: "I explored research questions around therapeutic targets and antibody-based approaches, bringing together scientific literature, biological rationale, and practical development considerations.", contributions: ["Reviewed evidence across potential therapeutic areas and target combinations.", "Organized findings into clear comparisons to support research discussions.", "Considered both biological promise and development challenges."], tools: ["Literature review", "Biotechnology", "Scientific communication"], note: "Some company research is confidential, so this public summary is intentionally high level." },
    { id: "hht", number: "02", title: "HHT mutation analysis", category: "GENETICS / DATA", summary: "Investigating patterns in HHT-related genes and what they may mean for research planning.", color: "lavender", motif: "chart", image: "", context: "Genetics analysis", overview: "I examined reported mutation patterns in ENG and ACVRL1, genes associated with hereditary hemorrhagic telangiectasia, and explored how geographic variation could inform questions about study-site selection.", contributions: ["Compared mutation distributions across available datasets and countries.", "Translated analytical findings into a concise research presentation.", "Documented limitations and questions for further investigation."], tools: ["Data analysis", "Genetics", "Research presentation"], note: "Public description omits internal strategy and unpublished results." },
    { id: "tb", number: "03", title: "TB transcriptomics", category: "COMPUTATIONAL BIOLOGY", summary: "Using gene-expression data to investigate biological responses to tuberculosis.", color: "sage", motif: "cells", image: "", context: "MIT Lauffenburger Lab", overview: "During a summer research experience at MIT, I worked on tuberculosis-related transcriptomic analysis and learned how computational approaches can help identify patterns in complex biological data.", contributions: ["Worked with transcriptomic research questions and computational analysis.", "Interpreted results in the context of underlying biology.", "Communicated findings to researchers."], tools: ["Transcriptomics", "Computational biology", "Research"] },
    { id: "pcbang", number: "04", title: "PC bangs & community", category: "FIELD RESEARCH / KOREA", summary: "Asking whether shared gaming spaces foster connection or reinforce isolation.", color: "blue", motif: "community", image: "", context: "Ewha summer study abroad", overview: "For a research project in Korea, I explored PC bangs as social spaces, especially how solo use, friendship groups, and gender shape people's experiences.", contributions: ["Conducted interviews with students and PC bang users.", "Compared individual experiences with broader questions about community and gender.", "Presented observations and questions for future research."], tools: ["Interviews", "Qualitative research", "Cross-cultural research"] },
    { id: "product", number: "05", title: "Anatomy of a bottle", category: "ENGINEERING / DESIGN", summary: "A component-by-component teardown of an insulated bottle, from vacuum walls to cost.", color: "yellow", motif: "bottle", image: "", context: "Engineering coursework", overview: "I broke down an insulated bottle into its key parts to understand how materials, manufacturing choices, and assembly contribute to performance and price.", contributions: ["Mapped the bottle's physical components and their functions.", "Examined insulation, sealing, and manufacturing choices.", "Built a preliminary materials and production cost estimate."], tools: ["Product teardown", "Materials", "Cost analysis"] },
    { id: "biosecurity", number: "06", title: "Biosecurity in education", category: "POLICY / RESEARCH", summary: "Looking at how emerging biology and security questions are taught and discussed.", color: "mint", motif: "document", image: "", context: "OpenBio fellowship", overview: "Through a biosecurity fellowship, I investigated how universities approach the social and security implications of biotechnology, connecting curriculum research with conversations and written analysis.", contributions: ["Reviewed curriculum and course offerings.", "Conducted interviews and synthesized recurring themes.", "Developed accessible written analysis for broader audiences."], tools: ["Curriculum analysis", "Interviews", "Writing"] }
  ],
  experience: [
    { years: "2026", role: "Research experience", organization: "Diagonal Therapeutics", description: "Therapeutic research, target evaluation, and scientific synthesis." },
    { years: "2025–26", role: "Biosecurity Fellow", organization: "OpenBio", description: "Explored biotechnology, education, and biosecurity through research and writing." },
    { years: "2024–present", role: "Medical Assistant / Admin", organization: "Mass General Brigham", description: "Supported patient care and clinical operations." },
    { years: "2024–present", role: "Cadet & Team Leader", organization: "Army ROTC", description: "Developing leadership through training, teamwork, and service." },
    { years: "2023", role: "Researcher", organization: "MIT Lauffenburger Lab", description: "Investigated tuberculosis-related transcriptomic data." }
  ]
};
